services:
  - docker

before_install:
  - docker pull pandoc/latex:2.7.3

script:
  - docker run --volume "$(pwd):/data" --user $(id -u):$(id -g) pandoc/latex:2.7.3 -o essay.pdf --filter pandoc-citeproc essay.md
